version: 2
jobs:
  test:
    working_directory: /go/src/github.com/kitsuyui/invisible
    docker:
      - image: golang:1.14.7-stretch@sha256:d0156fad86b712d8fa2fbb4ce3bb3751ff9db996a4f41352dcf76987bb850e33
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./bin/test.sh
            ./bin/coverage.sh
            bash <(curl -s https://codecov.io/bash)

  release:
    working_directory: /go/src/github.com/kitsuyui/invisible
    docker:
      - image: golang:1.14.7-stretch@sha256:d0156fad86b712d8fa2fbb4ce3bb3751ff9db996a4f41352dcf76987bb850e33
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
            BUILD_VERSION="$CIRCLE_TAG" ./bin/build.sh
            mkdir /tmp/releases
            mv ./build/invisible_* /tmp/releases
            ghr -u "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_TAG" /tmp/releases
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_release:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+.\d+$/
