name: Update gitignore file
on:
  schedule:
    # daily at 00:00
    - cron: '0 0 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  update-gitignore:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/gitignore-in.yml@3717c78af3a5e594b7a81b063276e15fac7e08fc
