name: golang-test

on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1

      - name: install dependencies
        run: go get -v -t -d ./...

      - name: test
        run: go test -v -cover -race -covermode=atomic -coverprofile=coverage.out ./...

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
