name: octocov
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  octocov:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: setup
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: 1.26.0

      - name: install dependencies
        run: go get -v -t -d ./...

      - name: lint
        run: go vet ./...

      - name: test
        run: go test -v -cover -race -covermode=atomic -coverprofile=coverage.out ./...

      # See also: https://github.com/k1LoW/octocov-action
      - name: Report coverage with octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: .octocov.yml
