name: Spellcheck
on:
  - pull_request
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check spelling
        uses: crate-ci/typos@master
        # typos is a Source code spell checker
        # https://github.com/crate-ci/typos
